// PORTED VERBATIM from 1click1story inline-0.js — style/mood/visual libraries + scene templates.
// ponytail: copied as-is so the engine matches the original output exactly; edit upstream meaning here only.

export const narrativeStyles = [
    { num: 0, name: "ไม่เลือก", icon: "⚪", desc: "ไม่ระบุ Narrative Style", personality: '' },
    { num: 1, name: "Hard Sell", icon: "👊", desc: "ดุดัน เร่งด่วน ฟาดด้วยโปรโมชั่น", personality: '[Hard Sell] 👊: ดุดัน เร่งด่วน ฟาดด้วยโปรโมชั่น "ซื้อเดี๋ยวนี้ พรุ่งนี้ราคาขึ้น! อย่ามัวแต่คิด!"' },
    { num: 2, name: "Soft Sell", icon: "✨", desc: "เพื่อนสาวเม้าท์มอย เนียนๆ ป้ายยา", personality: '[Soft Sell] ✨: เพื่อนสาวเม้าท์มอย เนียนๆ ป้ายยาแนวกันเอง "แก... ฉันไปเจออันนี้มา คือมันดีต่อใจมาก"' },
    { num: 3, name: "The Unboxer", icon: "📦", desc: "ตื่นเต้นเหมือนได้ของใหม่ บรรยายละเอียดยิบ", personality: '[The Unboxer] 📦: ตื่นเต้นเหมือนได้ของใหม่ บรรยาย Texture และสัมผัสละเอียดยิบ' },
    { num: 4, name: "The Skeptic", icon: "🧐", desc: "สายจับผิด ไม่เชื่อคำเคลมง่ายๆ", personality: '[The Skeptic] 🧐: สายจับผิด ไม่เชื่อคำเคลมง่ายๆ "จริงเหรอ? ไหนลองซิ ถ้าไม่ดีจริงแม่จะด่าให้"' },
    { num: 5, name: "FOMO Creator", icon: "🚨", desc: "กระตุ้นความกลัวตกกระแส", personality: '[FOMO Creator] 🚨: กระตุ้นความกลัวตกกระแส "ใครไม่มีคือเชยระเบิด! ของจะหมดใน 3 นาทีนี้แล้ว!"' },
    { num: 6, name: "Villain vs Hero", icon: "⚔️", desc: "ปีศาจ (ปัญหา) ปะทะ ฮีโร่ (สินค้า)", personality: '[Villain vs Hero] ⚔️: (ค่าเริ่มต้น) ปีศาจ (ปัญหา) ปะทะ ฮีโร่ (สินค้า) สู้กันแบบดุเดือด' },
    { num: 7, name: "Tough Love", icon: "🤬", desc: "ปากแจ๋วแต่หวังดี ด่ากราดเพื่อเตือนสติ", personality: '[Tough Love] 🤬: ปากแจ๋วแต่หวังดี ด่ากราดเพื่อเตือนสติ "หน้าพังขนาดนี้ยังไม่ดูแลอีกเหรอ! ตื่น!"' },
    { num: 8, name: "Tsundere", icon: "😳", desc: "ซึนเดระ ปากไม่ตรงกับใจ", personality: '[Tsundere] 😳: ซึนเดระ ปากไม่ตรงกับใจ "ไม่ได้อยากช่วยหรอกนะ... แต่เห็นแล้วมันขัดตา เอาไปใช้ซะ!"' },
    { num: 9, name: "The Nag", icon: "👵", desc: "มนุษย์ป้าขี้บ่น บ่นดินฟ้าอากาศ วกเข้าขายของ", personality: '[The Nag] 👵: มนุษย์ป้าขี้บ่น บ่นดินฟ้าอากาศ บ่นลูกหลาน แล้ววกเข้าขายของแบบงงๆ' },
    { num: 10, name: "Drama Queen", icon: "🎭", desc: "เล่นใหญ่รัชดาลัย เวิ่นเว้อเบอร์แรง", personality: '[Drama Queen] 🎭: เล่นใหญ่รัชดาลัย เวิ่นเว้อเบอร์แรง "โอ๊ยยยย ชีวิตฉันมันจบสิ้นแล้ว ถ้าไม่มีสิ่งนี้!"' },
    { num: 11, name: "Talking Object", icon: "🗣️", desc: "สิ่งของพูดได้ที่ชอบจิกกัดเจ้าของ", personality: '[Talking Object] 🗣️: สิ่งของพูดได้ที่ชอบจิกกัดเจ้าของ (เช่น ตู้เย็นที่บ่นคนแอบมาเปิดดูตอนตี 2)' },
    { num: 12, name: "Organ War", icon: "🧠", desc: "อวัยวะตีกันเอง เช่น ตับประท้วงสมอง", personality: '[Organ War] 🧠: อวัยวะตีกันเอง (เช่น ตับประท้วงสมองที่สั่งให้ดื่มแอลกอฮอล์)' },
    { num: 13, name: "Pet Translator", icon: "🐱", desc: "แปลภาษาหมา/แมว มนุษย์คือทาส", personality: '[Pet Translator] 🐱: แปลภาษาหมา/แมว ที่มองว่ามนุษย์คือทาสที่ต้องคอยประเคนของให้' },
    { num: 14, name: "Time Traveler", icon: "🛸", desc: "มาจากอนาคตปี 2090 บอกว่าล้าหลัง", personality: '[Time Traveler] 🛸: มาจากอนาคตปี 2090 "ยุคคุณยังใช้อันนี้อยู่เหรอ? ล้าหลังมาก! ที่นู่นเขาใช้..."' },
    { num: 15, name: "God vs Devil", icon: "😇", desc: "เทวดากับซาตานเถียงกันบนไหล่ซ้าย-ขวา", personality: '[God vs Devil] 😇😈: เทวดากับซาตานที่เถียงกันอยู่บนไหล่ซ้าย-ขวาของคุณ' },
    { num: 16, name: "The Geek", icon: "🤓", desc: "ข้อมูลแน่นปึก ศัพท์เทคนิคย่อยง่าย", personality: '[The Geek] 🤓: ใส่แว่น ข้อมูลแน่นปึก พูดศัพท์เทคนิคแต่ย่อยมาให้แล้วจนเข้าใจง่าย' },
    { num: 17, name: "Myth Buster", icon: "🔨", desc: "สายทำลายความเชื่อผิดๆ", personality: '[Myth Buster] 🔨: สายทำลายความเชื่อผิดๆ "ที่คุณเคยรู้มา... มันผิดหมดครับ! ความจริงคือ..."' },
    { num: 18, name: "Q&A Expert", icon: "🙋", desc: "ตอบคำถามทางบ้านแบบผู้เชี่ยวชาญ", personality: '[Q&A Expert] 🙋: มาแนวตอบคำถามทางบ้าน "มีคนถามเข้ามาเยอะมากว่า..."' },
    { num: 19, name: "News Anchor", icon: "🎙️", desc: "รายงานข่าวจริงจัง Breaking News", personality: '[News Anchor] 🎙️: รายงานข่าวแบบจริงจัง เกาะกระแส Breaking News ตลอดเวลา' },
    { num: 20, name: "Trends Hunter", icon: "📈", desc: "เจาะลึกเทรนด์โลก Deep Research", personality: '[Trends Hunter] 📈: (Deep Research) เจาะลึกเทรนด์โลก "รู้ยัง? ตอนนี้เทรนด์นี้มาแรงที่สุด"' },
    { num: 21, name: "The De-influencer", icon: "🛑", desc: "สายช็อตฟีล นักดับฝัน ทวนกระแส", personality: '[The De-influencer] 🛑: ทวนกระแส ไม่ป้ายยาแต่ "ห้ามซื้อ!" เปิดด้วยการด่าหรือบอกข้อเสียของฮิตๆ แล้วหักมุมมาขายของตัวเองที่ดีกว่า' },
    { num: 22, name: "The Fortune Teller", icon: "🔮", desc: "สายมูเตลู ทักจิตวิทยา ลึกลับน่าค้นหา", personality: '[The Fortune Teller] 🔮: สายมู "ถ้าคุณเลื่อนเจอคลิปนี้ จักรวาลกำลังบอกว่า..." แล้วเนียนผูกเข้ากับสรรพคุณสินค้าแบบซัพพอร์ตพลังชีวิต' },
    { num: 23, name: "The ASMR Seller", icon: "🤫", desc: "สายเสพเสียง ฮีลใจ กระซิบขาย", personality: '[The ASMR Seller] 🤫: ไม่พูดเยอะ (หรือพูดกระซิบ) เน้นเสียงก๊อบแก๊บของแพ็คเกจ เสียงเนื้อครีม สะกดจิตคนดูให้ดูจนจบ' },
    { num: 24, name: "The Over-Sharer", icon: "🤯", desc: "สายเล่าหมดเปลือก ดราม่าชีวิต", personality: '[The Over-Sharer] 🤯: เริ่มด้วยเรื่องส่วนตัวที่พีคมากๆ "ความลับที่ทำให้ฉันเกือบโดนไล่ออก..." แล้วเล่าโยงเข้าหาสินค้าแบบเนียนกริบ' },
    { num: 25, name: "The Main Character", icon: "💅", desc: "ตัวมัม ศูนย์กลางจักรวาล POV สุดเริ่ด", personality: '[The Main Character] 💅: เล่าผ่าน POV ของคนที่มั่นใจสุดๆ ชีวิตดีเริ่ด เชิดๆ หยิ่งๆ สินค้าคือพร็อพที่ขาดไม่ได้ในชีวิตสุดเพอร์เฟกต์' },
    { num: 26, name: "The Investigator", icon: "🕵️", desc: "สายสืบ ขุดคุ้ยหลังบ้าน แฉความลับ", personality: '[The Investigator] 🕵️: สวมบทนักสืบที่ไปขุดเจอ "ความลับ" ของวงการ หรือสูตรลับที่แบรนด์ไม่อยากให้รู้ เอา Fact มาแฉเทียบกัน' },
    { num: 27, name: "The Isan Joy", icon: "🇹🇭", desc: "ไทบ้านม่วนซื่น จ้วดจ้าด ภาษาอีสาน", personality: '[The Isan Joy] 🇹🇭: จ้วดจ้าด จริงใจ ขายขำด้วยภาษาอีสาน "เด้อ คักๆ จ้วด ตัวะ" เปิดคลิปมาด้วยพลังงานล้นๆ' },
    { num: 28, name: "The Southern Direct", icon: "🌴", desc: "คนใต้ใจเต็ม หรอยแรง ฟาดตรงๆ", personality: '[The Southern Direct] 🌴: พูดเร็ว กระชับ ไม่เยิ่นเย้อ "ของไม่ดีจริง ไม่เอามาบอกหรอก" ใช้ความจริงใจแบบดุดันเป็นตัวดึงดูด' },
    { num: 29, name: "The Northern Chill", icon: "🏔️", desc: "สาวเจียงใหม่ละมุน อู้กำเมืองช้าๆ", personality: '[The Northern Chill] 🏔️: โทนเสียงนุ่มนวล อู้กำเมืองช้าๆ เนิบๆ สร้างฟีลลิ่งผ่อนคลาย ค่อยๆ เล่าให้คนดูเคลิ้มตาม' },
    { num: 30, name: "The Sassy Queen", icon: "👑", desc: "ตัวมารดาโฮ่งๆ จริตตัวแม่ ศัพท์โซเชียลฉ่ำ", personality: '[The Sassy Queen] 👑: จริตเริ่ด มั่นใจ ใช้ศัพท์วัยรุ่น/กะเทย "โฮ่งมาก ฉ่ำ จึ้ง คุณน้า" จังหวะการเล่าเรื่องต้องโบ๊ะบ๊ะ' },
    { num: 31, name: "The Gossiper", icon: "🗣️", desc: "สายเผือก ป้าข้างบ้าน ซุบซิบแล้ววกขาย", personality: '[The Gossiper] 🗣️: Hook โหดด้วย "แกร ชั้นไปรู้อะไรมา..." หรือ "อันนี้ไม่ได้นินทานะ แต่..." กระตุ้นต่อมเผือกแล้วพลิกฉากเข้าสินค้า' },
    { num: 32, name: "The Self-Made", icon: "💰", desc: "วัยรุ่นสร้างตัว ทรงซ้อ อวดความสำเร็จ", personality: '[The Self-Made] 💰: เล่า Story ความยากลำบากในอดีต ตัดภาพมาที่ความสำเร็จปัจจุบัน (รถสปอร์ต ทอง เงินก้อน) แล้วขมวดจบว่าสินค้านี้คือตัวช่วย' },
    { num: 33, name: "The Prankster Couple", icon: "💑", desc: "คู่รักหยุมหัว แกล้งแฟน บ่นผัว/เมีย", personality: '[The Prankster Couple] 💑: ดึงคนดูด้วยความดราม่าหรือความตลกในครอบครัว เปิดคลิปด้วยการด่าผัว หรือแกล้งเมีย แล้วให้สินค้าเป็นตัวแก้ปัญหา' },
    { num: 34, name: "The Underdog", icon: "🥊", desc: "สู้ชีวิตแต่ชีวิตสู้กลับ ดราม่าซวยซ้ำซ้อน", personality: '[The Underdog] 🥊: เริ่มด้วยเรื่องซวยๆ ซ้ำซ้อนที่คนส่วนใหญ่ relate ได้ (เงินเดือนออกปุ๊บหมดปั๊บ) แล้วจบด้วยการเจอสินค้าที่เหมือนสวรรค์มาโปรด' },
    { num: 35, name: "The Voiceover Troll", icon: "🎤", desc: "นักพากย์นรก พากย์คลิปแปลกๆ กวนๆ", personality: '[The Voiceover Troll] 🎤: เอาคลิปแปลกๆ หรือคลิปสัตว์เลี้ยงมาพากย์เสียงทับแบบคนละเรื่องเดียวกัน สร้างความงงให้หยุดดู แล้วหักมุมขายของตอนท้าย' },
    { num: 36, name: "The Fangirl", icon: "😍", desc: "ติ่งอวยยศ หวีดร้องสุดเสียง ป้ายยาแบบคลั่งรัก", personality: '[The Fangirl] 😍: ใช้จริตแฟนคลับที่กำลังเห่อ "แก มันดีมากกกก นึกว่าสวรรค์ประทาน" แอคติ้งใหญ่ เล่นใหญ่ ขายความแพสชั่นที่มีต่อสินค้า' },
    { num: 37, name: "The Local Guru", icon: "🧓", desc: "สูตรผีบอก ภูมิปัญญาชาวบ้าน สูตรลับ", personality: '[The Local Guru] 🧓: สร้างความขลัง "สูตรนี้ปู่ย่าตายายบอกมา..." หรือ "ความลับที่คลินิกไม่อยากให้รู้" ผสมผสานความเชื่อเก่าๆ เข้ากับสินค้ายุคใหม่' },
    { num: 38, name: "The Mindset Coach", icon: "🧠", desc: "ไลฟ์โค้ชกระชากสติ คำคมกระแทกใจ", personality: '[The Mindset Coach] 🧠: Hook แรงๆ "ถ้าคุณยังทำสิ่งนี้อยู่ เลื่อนผ่านไปเลย!" ดึงคนให้อยากรู้ว่าตัวเองทำผิดตรงไหน แล้วค่อยๆ ตะล่อมให้ความรู้และปิดการขาย' },
    { num: 39, name: "The Satirist", icon: "🎭", desc: "สายแซะสังคม หยิบกระแสข่าวมาเสียดสี", personality: '[The Satirist] 🎭: เกาะกระแส Real-time (ข่าวรถติด ข่าวการเมือง ข่าวดารา) เอามาล้อเลียนขำๆ แล้ววกเข้าสินค้าแบบหน้าดื้อๆ คนดูจะชอบความตลกร้ายและแชร์ต่อ' },
    { num: 40, name: "The Glutton", icon: "🍔", desc: "สายสวบดุดัน รีวิวแบบคนหิวโหย อร่อยแสงออกปาก", personality: '[The Glutton] 🍔: ถ้าเป็นของกิน เน้นภาพและการบรรยายที่กระตุ้นความอยากอาหารขั้นสุด เสียงเคี้ยว เสียงกลืน ต้องชัดเจน แอคติ้งเว่อร์วัง' }
];

export const moodKeywords = [
    { id: "none", name: "ไม่เลือก", icon: "⚪", desc: "ไม่ระบุ Mood & Tone" },
    { id: "cinematic_standard", name: "Cinematic Standard", icon: "🎬", desc: "มาตรฐานภาพยนตร์ แสงเงาสมบูรณ์" },
    { id: "bright_airy", name: "Bright & Airy", icon: "☀️", desc: "สว่าง สดใส อากาศถ่ายเท" },
    { id: "warm_cozy", name: "Warm & Cozy", icon: "🔥", desc: "อบอุ่น เป็นกันเอง เหมือนอยู่บ้าน" },
    { id: "minimalist_clean", name: "Minimalist Clean", icon: "⬜", desc: "เรียบหรู น้อยแต่มาก" },
    { id: "luxury_gold", name: "Luxury Gold", icon: "👑", desc: "หรูหรา อลังการ โทนทอง" },
    { id: "dark_gritty", name: "Dark & Gritty", icon: "🌑", desc: "มืดหม่น ดิบเถื่อน" },
    { id: "red_alert", name: "Red Alert", icon: "🔴", desc: "โทนแดง อันตราย เร่งด่วน" },
    { id: "horror_thriller", name: "Horror/Thriller", icon: "👻", desc: "สยองขวัญ บรรยากาศน่ากลัว" },
    { id: "action_explosive", name: "Action Explosive", icon: "💥", desc: "ตื่นเต้น เร้าใจ แอ็คชั่น" },
    { id: "grunge_dirty", name: "Grunge/Dirty", icon: "🎸", desc: "ดิบ สตรีท เท่แนวเท่" },
    { id: "cyberpunk_neon", name: "Cyberpunk Neon", icon: "🌆", desc: "นีออนหลากสี โลกอนาคต" },
    { id: "pastel_dreamy", name: "Pastel Dreamy", icon: "🌸", desc: "พาสเทล นุ่มนวล ฝันหวาน" },
    { id: "futuristic_scifi", name: "Futuristic Sci-Fi", icon: "🚀", desc: "ล้ำสมัย เทคโนโลยีขั้นสูง" },
    { id: "magical_fantasy", name: "Magical Fantasy", icon: "🧙", desc: "เพ้อฝัน ระยิบระยับ มีมนตร์" },
    { id: "wes_anderson", name: "Wes Anderson", icon: "🏨", desc: "สมมาตร พาสเทลจัดวา เอกลักษณ์" },
    { id: "retro_90s", name: "Retro 90s", icon: "📼", desc: "ย้อนยุค Noise ฟิล์มเก่า" },
    { id: "fresh_cool", name: "Fresh & Cool", icon: "🧊", desc: "สดชื่น เย็นสบาย ฟ้าเขียว" },
    { id: "romantic_rose", name: "Romantic Rose", icon: "🌹", desc: "หวานซึ้ง โรแมนติก ชมพูอ่อน" },
    { id: "nature_organic", name: "Nature Organic", icon: "🌿", desc: "ธรรมชาติ ใบไม้ แสงแดด" },
    { id: "mystery_noir", name: "Mystery Noir", icon: "🕵️", desc: "ลึกลับ แสงเงาตัดกันรุนแรง" },
    // 🇹🇭 สายฮิตติดเทรนด์ไทย
    { id: "mute_earth_tone", name: "Mute & Earth Tone", icon: "🤎", desc: "โทนตุ่นละมุน เอิร์ธโทน คาเฟ่เกาหลีทิพย์" },
    { id: "mutelu_mystical", name: "Mutelu Mystical", icon: "🕉️", desc: "มนตร์ขลัง แสงเทียนสลัว ควันธูป สายมูเตลู" },
    { id: "thai_street_night", name: "Thai Street Night", icon: "🍜", desc: "แสงไฟนีออนร้านอาหาร ควันฉุย สตรีทฟู้ดเรียลๆ" },
    { id: "rainy_lonely", name: "Rainy & Lonely", icon: "🌧️", desc: "ฝนตก เหงาหม่น โทนฟ้าเทา ฟีลคนอกหัก" },
    { id: "thai_vintage_town", name: "Thai Vintage Town", icon: "🎞️", desc: "ฟิล์มเก่า สีอมเหลืองอบอุ่น สไตล์ทรงวาด/เยาวราช" },
    { id: "y2k_thai_pop", name: "Y2K Thai Pop", icon: "🪩", desc: "สีสันฉูดฉาด จี๊ดจ๊าด ซ่าๆ วัยรุ่นเทสดี" },
    { id: "vivid_thai_summer", name: "Vivid Thai Summer", icon: "☀️", desc: "สีสดจัดจ้าน สู้แดด ทะเลเดือด ร้อนระอุ" },
    { id: "rich_flex", name: "Rich & Flex", icon: "🤑", desc: "แสงส่องประกาย เงินทอง โชว์รวยแบบตะโกน" },
    { id: "local_homey", name: "Local Homey", icon: "🏡", desc: "แสงธรรมชาติ เรียบง่าย บ้านๆ จริงใจ" },
    { id: "surreal_comedy", name: "Surreal Comedy", icon: "🤡", desc: "สีสันตัดกัน โบ๊ะบ๊ะ ฟีลซิตคอมตลกไทย" },
    // 🌍 สาย Viral ตปท. & TikTok Trends
    { id: "ugc_raw", name: "UGC Raw / Unfiltered", icon: "📱", desc: "กล้องมือถือสั่นๆ เรียลๆ ไม่แต่งสี ป้ายยาเนียน" },
    { id: "fisheye_ultrawide", name: "Fisheye / Ultra Wide", icon: "👁️", desc: "เลนส์ตาปลา บิดเบี้ยว ใกล้ชิด กวนๆ" },
    { id: "bodycam_pov", name: "Bodycam / POV Action", icon: "🏃", desc: "มุมกล้องแทนสายตา สั่นๆ เหมือนอยู่ในเหตุการณ์จริง" },
    { id: "hyper_macro", name: "Hyper-Macro Satisfying", icon: "🔍", desc: "ซูมชัดตาแตก เห็นเทกซ์เจอร์ ฟินๆ สไตล์ ASMR" },
    { id: "glitch_distorted", name: "Glitch & Distorted", icon: "📺", desc: "ภาพแตก สัญญาณแทรก ดึงสติคนดู" },
    { id: "old_money", name: "Old Money Aesthetic", icon: "🕰️", desc: "เรียบหรู ดูแพง คลาสสิก ไม่ตะโกน" },
    { id: "lofi_chillhop", name: "Lo-Fi Chillhop", icon: "🎧", desc: "แสงสลัว โทนม่วงชมพู นั่งชิลดึกๆ" },
    { id: "liminal_dreamcore", name: "Liminal Space / Dreamcore", icon: "🚪", desc: "เวิ้งว้าง คุ้นเคยแต่ประหลาด ดึงอารมณ์ร่วม" },
    { id: "cottagecore", name: "Cottagecore / Fairy Tale", icon: "🍄", desc: "ธรรมชาติฟุ้งๆ ดอกไม้ นิทาน ชวนฝัน" },
    { id: "paparazzi_flash", name: "Paparazzi Flash", icon: "📸", desc: "แสงแฟลชสาดแรงๆ ดิบๆ เหมือนแอบถ่ายคนดัง" }
];

export const visualStyles = [
    // ⚪ None
    { id: "none", name: "ไม่เลือก", icon: "⚪", desc: "ไม่ระบุ Visual Style", category: "None", prompt: "" },
    // ✨ Mainstream
    { id: "real_cinematic", name: "Real Cinematic", icon: "🎬", desc: "คนจริง แสงสีอลังการเหมือนหนังฮอลลีวูด", category: "Mainstream", prompt: "photorealistic cinematic film still, Hollywood movie quality, dramatic lighting, lens flare, shallow depth of field, 35mm film grain" },
    { id: "disney_pixar_3d", name: "Disney / Pixar 3D", icon: "🏰", desc: "3D ตาโตน่ารักแบบการ์ตูนฝรั่ง", category: "Mainstream", prompt: "3D animated CGI feature film character, high-end premium 3D studio animation style, expressive eyes, soft smooth skin texture, subsurface scattering, next-gen graphics render, masterpiece" },
    { id: "ghibli", name: "Studio Ghibli", icon: "🌿", desc: "ลายเส้นสีน้ำ อะนิเมะญี่ปุ่นยุคเก่า อบอุ่น", category: "Mainstream", prompt: "Studio Ghibli anime style, watercolor painting, soft pastel colors, hand-drawn animation, warm nostalgic atmosphere, lush nature details, Hayao Miyazaki inspired" },
    // 🧸 Craft & Tactile
    { id: "claymation", name: "Claymation", icon: "🎨", desc: "ดินน้ำมัน แบบ Pingu / Wallace & Gromit", category: "Craft", prompt: "claymation stop-motion style, clay sculpted characters, fingerprint textures on surface, plasticine material, warm studio lighting, Wallace and Gromit style" },
    { id: "crochet", name: "ถักไหมพรม (Crochet)", icon: "🧶", desc: "ทุกอย่างดูเหมือนทำจากไหมพรม", category: "Craft", prompt: "amigurumi crochet style, knitted yarn texture, soft wool material, handmade craft aesthetic, cozy warm colors, detailed stitch patterns visible" },
    { id: "plushie", name: "ตุ๊กตาผ้าขนฟู (Plushie)", icon: "🧸", desc: "ขนปุยๆ นุ่มนิ่ม น่ากอด", category: "Craft", prompt: "plushie felt toy style, soft fluffy fur texture, stuffed animal aesthetic, button eyes, fabric stitching details, kawaii cute proportions" },
    { id: "paper_cutout", name: "กระดาษตัด (Paper Cut)", icon: "✂️", desc: "Stop Motion กระดาษซ้อนกัน อาร์ตเท่", category: "Craft", prompt: "paper cutout stop motion style, layered paper craft, construction paper textures, visible paper edges and shadows, colorful collage aesthetic" },
    // 📺 Nostalgia & Iconic
    { id: "dragonball", name: "Dragon Ball", icon: "🐉", desc: "ลายเส้นกล้ามๆ ตาคมๆ แบบโทริยาม่า", category: "Nostalgia", prompt: "Dragon Ball anime style, Akira Toriyama art style, bold outlines, dynamic action pose, energy aura effects, muscular proportions, shonen manga aesthetic" },
    { id: "90s_anime", name: "90s Japanese Anime", icon: "🌙", desc: "ตาหวานยุคเซเลอร์มูน แสงฟุ้งๆ", category: "Nostalgia", prompt: "1990s Japanese anime style, Sailor Moon aesthetic, soft diffused lighting, sparkle effects, cel-shaded animation, pastel color palette, dreamy atmosphere" },
    { id: "gta_style", name: "GTA Loading Screen", icon: "🔫", desc: "ภาพวาดกึ่งจริง ขอบดำเข้ม ดิบเท่", category: "Nostalgia", prompt: "GTA game loading screen art style, semi-realistic illustration, bold black outlines, high contrast, urban gritty aesthetic, satirical portrait style" },
    // 🎨 Artistic
    { id: "watercolor", name: "สีน้ำ (Watercolor)", icon: "🎨", desc: "ละมุน อาร์ตๆ สายมู เล่าเรื่องอดีต", category: "Artistic", prompt: "watercolor painting style, soft washes of color, visible brush strokes, wet-on-wet technique, delicate translucent layers, artistic illustration" },
    { id: "chalk_art", name: "ชอล์ก (Chalk Art)", icon: "☕", desc: "ฟีลเหมือนเขียนบนกระดานดำร้านกาแฟ", category: "Artistic", prompt: "chalk art on blackboard style, white and colored chalk drawing, chalkboard texture background, hand-drawn sketch aesthetic, cafe menu board style" },
    { id: "oil_painting", name: "Oil Painting", icon: "🖼️", desc: "สีน้ำมัน รอยแปรงชัดๆ ขลังมีพลัง", category: "Artistic", prompt: "classical oil painting style, visible impasto brush strokes, rich deep colors, dramatic chiaroscuro lighting, Renaissance master painting technique" },
    { id: "pop_art", name: "Pop Art", icon: "💥", desc: "คอมมิคฝรั่ง สีฉูดฉาด แซะแรงๆ", category: "Artistic", prompt: "Pop Art style, Roy Lichtenstein inspired, Ben-Day dots, bold primary colors, comic book aesthetic, speech bubbles, halftone pattern, Andy Warhol influence" },
    // 🕹️ Modern Digital
    { id: "pixel_art", name: "Pixel Art (8-bit)", icon: "👾", desc: "เกมยุคเก่า Retro สาย Gamer", category: "Digital", prompt: "pixel art 8-bit retro game style, low resolution aesthetic, visible square pixels, limited color palette, nostalgic video game graphics, NES/SNES era" },
    { id: "cyberpunk_neon", name: "Cyberpunk / Neon", icon: "🌃", desc: "แสงนีออนจัดจ้าน ล้ำยุค", category: "Digital", prompt: "cyberpunk neon style, vibrant neon lights, dark futuristic cityscape, holographic effects, rain-slicked streets, blade runner aesthetic, purple and cyan glow" },
    { id: "vector_flat", name: "Vector Flat", icon: "📱", desc: "ลายเส้นสะอาด แบบแอปฯ Professional", category: "Digital", prompt: "flat vector illustration style, clean geometric shapes, minimal shading, modern app UI aesthetic, solid colors, professional infographic style" },
    { id: "lego_style", name: "Lego Style", icon: "🧱", desc: "ทุกอย่างกลายเป็นตัวต่อ Lego แปลกตา", category: "Digital", prompt: "Lego brick style, everything made of Lego blocks, plastic toy aesthetic, Lego minifigure characters, bright primary colors, toy photography style" },
    // 🗿 Unique
    { id: "vaporwave", name: "Vaporwave", icon: "🏛️", desc: "ชมพูม่วง รูปปั้นกรีก แสงฟุ้ง สายอาร์ต", category: "Unique", prompt: "vaporwave aesthetic, pink and purple gradient, Greek marble statue, retro 80s computer graphics, glitch effects, palm trees, sunset grid, lo-fi dream" },
    { id: "emoji_icon", name: "Emoji / Icon Style", icon: "😊", desc: "ไอคอนกลมๆ น่ารักเหมือนอิโมจิ สบายตา", category: "Unique", prompt: "emoji icon style, round cute characters, simple flat design, bright cheerful colors, minimal details, emoticon aesthetic, app icon style" },
    // 🇹🇭 Thai & Asian Pop Culture
    { id: "thai_temple_mural", name: "Thai Temple Mural", icon: "🛕", desc: "จิตรกรรมฝาผนัง วิจิตร ชดช้อย ลายไทยประยุกต์", category: "Thai & Asian", prompt: "Thai temple mural painting style, traditional Thai art, intricate gold leaf details, Buddhist iconography, elegant flowing lines, royal Thai aesthetic" },
    { id: "thai_retro_poster", name: "Thai Retro Poster", icon: "🎬", desc: "โปสเตอร์หนังไทยโบราณ สีสดจัดจ้าน ฟอนต์อ้วนวาดมือ", category: "Thai & Asian", prompt: "vintage Thai movie poster style, bold hand-painted typography, vibrant saturated colors, 1970s Thai cinema aesthetic, dramatic composition" },
    { id: "webtoon_manhwa", name: "Webtoon / Manhwa", icon: "📖", desc: "ลายเส้นเว็บตูน พระเอกหล่อเทพ นางเอกสวยฉ่ำ", category: "Thai & Asian", prompt: "Korean webtoon manhwa style, beautiful character design, soft shading, romantic atmosphere, vertical scroll comic format, clean line art" },
    { id: "thai_ghost_comic", name: "Thai Ghost Comic", icon: "👻", desc: "การ์ตูนผีเล่มละบาท ลายเส้นขาวดำ สยองขวัญ ดิบๆ", category: "Thai & Asian", prompt: "Thai horror comic style, black and white ink drawing, creepy atmosphere, vintage Thai ghost story aesthetic, dramatic shadows, horror manga influence" },
    { id: "y2k_purikura", name: "Y2K Purikura", icon: "📸", desc: "ตู้สติกเกอร์ญี่ปุ่น ตาโตวิ้งวับ สีพาสเทล ฟรุ้งฟริ้ง", category: "Thai & Asian", prompt: "Japanese purikura photo booth style, big sparkling eyes, pastel colors, cute decorative frames, glitter effects, Y2K kawaii aesthetic" },
    { id: "ukiyo_e", name: "Ukiyo-e", icon: "🌊", desc: "ภาพพิมพ์ไม้ญี่ปุ่นโบราณ ลายเส้นคลื่นน้ำ ซามูไร", category: "Thai & Asian", prompt: "Japanese ukiyo-e woodblock print style, traditional wave patterns, bold outlines, flat color areas, Hokusai inspired, Edo period aesthetic" },
    // 🎨 Trendy & Viral Aesthetics
    { id: "doodle_art", name: "Doodle Art", icon: "✏️", desc: "ขยุกขยิกสไตล์ ลายเส้นวาดเล่นเต็มเฟรม กวนๆ", category: "Trendy", prompt: "doodle art style, hand-drawn sketchy lines, playful illustrations, filled frame composition, black ink on white, casual fun aesthetic" },
    { id: "double_exposure", name: "Double Exposure", icon: "🌲", desc: "ภาพซ้อนทับ ภาพคนซ้อนวิวธรรมชาติ อาร์ตๆ ลึกซึ้ง", category: "Trendy", prompt: "double exposure photography style, portrait merged with nature landscape, silhouette blending, artistic overlay, dreamy atmospheric effect" },
    { id: "risograph", name: "Risograph Print", icon: "🖨️", desc: "งานพิมพ์ริโซ่ สีสกรีนเป็นจุดๆ ฟีลนิตยสารอินดี้", category: "Trendy", prompt: "risograph print style, halftone dot pattern, limited color palette, slight misregistration, indie zine aesthetic, textured paper look" },
    { id: "origami", name: "Origami", icon: "🦢", desc: "ศิลปะพับกระดาษ ทุกอย่างพับจากกระดาษ มีมิติแสงเงา", category: "Trendy", prompt: "origami paper folding style, geometric paper sculptures, crisp folds and creases, soft shadows, minimalist Japanese aesthetic" },
    { id: "surrealism", name: "Surrealism", icon: "🎭", desc: "ศิลปะเหนือจริง ภาพสไตล์ดาลี ความฝันบิดเบี้ยว", category: "Trendy", prompt: "surrealist art style, Salvador Dali inspired, dreamlike impossible scenes, melting objects, bizarre juxtapositions, subconscious imagery" },
    { id: "gothic_dark_fantasy", name: "Gothic Dark Fantasy", icon: "🏰", desc: "ดาร์กแฟนตาซี ปราสาทมืด หม่นๆ อลังการ ลึกลับ", category: "Trendy", prompt: "gothic dark fantasy style, medieval castle, dramatic dark atmosphere, mysterious fog, ornate architecture, dark romantic aesthetic" },
    // 💻 Advanced Digital & 3D
    { id: "isometric_3d", name: "Isometric 3D", icon: "🏗️", desc: "3D มุมมองเฉียง จำลองห้องหรือเมืองจากมุมเฉียงบน", category: "Advanced 3D", prompt: "isometric 3D illustration style, 30-degree angle view, miniature diorama aesthetic, clean geometric shapes, soft shadows, architectural visualization" },
    { id: "low_poly_3d", name: "Low-Poly 3D", icon: "💎", desc: "3D เหลี่ยมก้อนๆ สไตล์เกมยุค PS1 คลาสสิก", category: "Advanced 3D", prompt: "low-poly 3D style, geometric faceted surfaces, PS1 era video game aesthetic, limited polygon count, nostalgic retro 3D graphics" },
    { id: "glitch_art", name: "Glitch Art", icon: "📺", desc: "ภาพดิจิทัลพังๆ สัญญาณแทรก สีรุ้งเหลื่อมๆ", category: "Advanced 3D", prompt: "glitch art style, digital corruption effects, RGB color splitting, scan lines, data moshing, broken signal aesthetic, cyberpunk error" },
    { id: "neon_line_art", name: "Neon Line Art", icon: "💡", desc: "เส้นแสงนีออน ลายเส้นเรืองแสงบนพื้นดำ ล้ำสมัย", category: "Advanced 3D", prompt: "neon line art style, glowing light trails on dark background, luminous outlines, electric blue and pink, futuristic minimalist" },
    { id: "cyber_sigilism", name: "Cyber Sigilism", icon: "⚔️", desc: "รอยสักสายดาร์ก Y2K ลายเส้นแหลมๆ คมๆ", category: "Advanced 3D", prompt: "cyber sigilism style, sharp angular tribal tattoo designs, dark Y2K aesthetic, symmetrical patterns, black ink on skin, edgy street fashion" },
    { id: "hyper_realistic", name: "Hyper-Realistic Portrait", icon: "👤", desc: "ภาพคนสมจริงตาแตก ชัดทุกรูขุมขน แสงเงาเป๊ะ", category: "Advanced 3D", prompt: "hyper-realistic portrait photography, extreme detail, visible skin pores, professional studio lighting, 8K resolution, photorealistic rendering" },
    { id: "steampunk", name: "Steampunk", icon: "⚙️", desc: "เครื่องจักรไอน้ำยุคเก่า ฟันเฟือง ทองเหลือง วิกตอเรีย", category: "Advanced 3D", prompt: "steampunk style, Victorian era machinery, brass gears and cogs, steam-powered technology, industrial revolution aesthetic, retro-futuristic" },
    { id: "polaroid_snapshot", name: "Polaroid Snapshot", icon: "🖼️", desc: "โพลารอยด์วินเทจ ขอบขาว แสงแฟลชสาด ภาพซีดๆ", category: "Advanced 3D", prompt: "polaroid instant photo style, white border frame, flash photography, slightly faded colors, nostalgic vintage memory aesthetic, casual snapshot" }
];

export const sceneTemplates = {
    1: { name: "Hook - Pattern Interrupt", tag: "HOOK",
         expression: "shocked, wide eyes, mouth open in disbelief",
         action: "dramatic reaction pose, pointing at something unexpected",
         extra_img: "visual curiosity, odd element, high contrast",
         extra_vid: "Sudden dramatic entrance, breaking the fourth wall",
         camera: "Quick zoom-in to face, dutch angle" },
    2: { name: "ปัญหา / ความขัดแย้ง", tag: "",
         expression: "frustrated, annoyed, confused",
         action: "arms crossed, shaking head, looking at the problem",
         extra_img: "",
         extra_vid: "Expressing frustration with exaggerated body language",
         camera: "Medium shot, slight pan left" },
    3: { name: "เปิดตัว / ค้นพบ", tag: "",
         expression: "surprised, excited, eyes sparkling",
         action: "discovering something amazing, holding up the product",
         extra_img: "",
         extra_vid: "Eyes light up, dramatic reveal moment",
         camera: "Dolly zoom, dramatic reveal angle" },
    4: { name: "สาธิต / พิสูจน์", tag: "",
         expression: "confident, smiling, demonstrating",
         action: "showing the product in action, demonstrating features",
         extra_img: "",
         extra_vid: "Confidently showing product features with hand gestures",
         camera: "Close-up on product, then pull back to character" },
    5: { name: "ผลลัพธ์ / เปรียบเทียบ", tag: "",
         expression: "amazed, impressed, nodding with approval",
         action: "showing before/after, comparing results",
         extra_img: "",
         extra_vid: "Dramatic comparison moment, jaw drop reaction",
         camera: "Split-screen feel, side angle" },
    6: { name: "Social Proof / ยืนยัน", tag: "",
         expression: "proud, reassuring, trustworthy smile",
         action: "giving thumbs up, showing testimonials",
         extra_img: "",
         extra_vid: "Breaking into a confident dance or celebration",
         camera: "Medium shot, eye-level, stable" },
    7: { name: "Shoppertainment Tie-in", tag: "SELL",
         expression: "excited, persuasive, friendly wink",
         action: "holding the product packaging, pointing at camera",
         extra_img: "holding the product packaging, pointing at camera, authentic look",
         extra_vid: "Showing product to camera, pointing at link",
         camera: "Close-up on product in hand, then face" },
    8: { name: "Closing - Emotional ROI", tag: "CLOSE",
         expression: "warm smile, waving, urgent but friendly",
         action: "holding the product packaging, pointing at camera, showing price/promo",
         extra_img: "holding the product packaging, pointing at camera, authentic look",
         extra_vid: "Showing product to camera, pointing at link, waving goodbye",
         camera: "Pull back to full body, then quick zoom to product" }
};
